### ISSUE TITLE
Provider Configurator SMS

### ISSUE THREAD

**Issue by Translator5** [ArchiDroid/android_device_samsung_i9300#103]
If you use a new SIM-Provider and put the SIM the 1st time in, 
you will get the configuration sms, but since Beta 1 (cm12 5.0) this message is vanish. 
I know it works but I never saw this sms reach my phone.
Already tried very often.

**Comment by JustArchi** [comment]
SMSes sent while your SIM was unregistered properly arrive next time you register to the network.

Either you provide some log telling me what is wrong (logcat -b radio) or sample way to reproduce. Until then, this is not going to be considered.

**Comment by Translator5** [comment]
No I'm sure, it isn't because of that, and I do not mean the standard sms, I mean the APN-Instalation Notification SMS, this is something other kind of.

**Comment by JustArchi** [comment]
Try to `logcat -b radio`, send your special SMS and see what logs say.

**Comment by badlorg** [comment]
Morning, here is the logcat on s3's friend. 
https://drive.google.com/file/d/0B94g3GF6NquLZ3g0aXFORnhFLXM/view?usp=sharing

**Comment by JustArchi** [comment]
```
D/RILJ    ( 4872): [9742]> REQUEST_GET_NEIGHBORING_CELL_IDS [SUB0]
D/RILC    ( 1961): RequestComplete, RIL_SOCKET_1
E/RILC    ( 1961): Send Response to RIL_SOCKET_1
D/RilRequest( 4872): [9742]< REQUEST_GET_NEIGHBORING_CELL_IDS error: com.android.internal.telephony.CommandException: REQUEST_NOT_SUPPORTE
```

Seems connected to https://github.com/ArchiDroid/android_device_samsung_i9300/issues/93

**Comment by badlorg** [comment]
I think yeah. RIl issues? can tell my friend to try
su
restorecon /efs?

**Comment by JustArchi** [comment]
Re-evaluate this in build 7 please. I think it should be fixed as I fixed mobile networks search as well.

**Comment by badlorg** [comment]
Good Job Archi! everything works! :+1:  Here is the logcat to see.
https://drive.google.com/file/d/0B94g3GF6NquLSGF0TzY4aGd0ZXM/view?usp=sharing

**Comment by JustArchi** [comment]
Great to hear that, closed then.
