### ISSUE TITLE
ROM can't read external SD card properly

### ISSUE THREAD

**Issue by GTP95** [ArchiDroid/android_device_samsung_i9300#116]
Files on external SD card aren't read properly by Android. File manager can see them but I tried to play music on SD card both with the stock music app and with Shuttle but they fail. Gallery doesn't display images on SDcard properly and when I try to open videos on SDcard it says that can't play the file. I also tried to open a password database I have on SDcard with KeepassDroid but it says that can't find the file although I've triple checked the path and it's correct. All those problems reported so far are logged here: http://pastebin.com/bf19xrdy. I'm sure that this is an Android problem because I've inserted the microSD directly in my laptop and I was able to play music but then I reinserted it in my phone and connecting it to the laptop the computer fails to play music. This second part is logged here: https://app.box.com/s/6s3iysug6z6t6sgk3mke0o5zejwpom4z (sorry but for some reason this log exceeded the size limit for free users of pastebin). My microSD is formatted in Ext4, should I change filesystem?
Thanks in advance for your help.

**Comment by JustArchi** [comment]
Although this isn't device-based issue, I suggest sd-card format.

**Comment by JustArchi** [comment]
(Probably EXT4 is not natively supported by CM when put on sd-card, as it's missing SELinux context, I'm not going to fix it, as it's not device-based issue, not a bug either)

**Comment by GTP95** [comment]
I switched from FAT32 to Ext4 because I needed to create a simbolic link but I've read on a forum that FAT32 doesn't support them. Does exFAT support simlink? If not, could you please suggest me a filesystem that support them and would be fine on a SD? Maybe Ext3?

**Comment by JustArchi** [comment]
Noone, Ext4 is the closest you can get, but due to the fact that nobody added proper EXT4 support for extsd cards in CM, you'll face various issues. Perhaps SELinux could help.

**Comment by GTP95** [comment]
Thanks a lot for your quick and helpful support. I'll see if I can modify SELinux in some way and if doesn't helps I'll switch to exFAT. Too bad CyanogenMod does't support EXT4 on SD cards, I hope somebody adds proper support in the future since this is one of the most used filesystems in the GNU/Linux world.

**Comment by GTP95** [comment]
For everyone who may have this issue: permessive SELinux doesn't help, I switched to exFAT and now everything seems fine.
