### ISSUE TITLE
Camera crashes

### ISSUE THREAD

**Issue by JustArchi** [ArchiDroid/android_device_samsung_i9300#12]
Especially due to switching from back to front and vice versa.

**Comment by vishnu9009** [comment]
Plz fix this camera and Wi-Fi bug asap.
I want to use this rom as my daily driver.
And i also want to know if this rom has the bug(can't connect to camera) just like in cm11 . it's very frustrating in cm11.

**Comment by CyberianIce** [comment]
Entering google camera cause black screen freeze (hw reboot required)

**Comment by MarcKe** [comment]
This one is fixed. Other crashes not noticed so far.
