### ISSUE TITLE
[Build 9] WiFi-Direct does not work

### ISSUE THREAD

**Issue by thopiekar** [ArchiDroid/android_device_samsung_i9300#122]
Checked the changelog for the new changes and was happy about the new changes - most of all about the HW en-/decoder changes.
Just wanted to try miracast, but noticed Wifi-Direct does not work.
Like in CM11 it isn't possible to change the device name and look for devices around :sob:

**Comment by JustArchi** [comment]
Unless it worked in B7, I'm afraid I'm not able to fix that. Did it?

**Comment by thopiekar** [comment]
Can't tell anything about B7, was (sadly) not using it as I was waiting for more important fixes (here the HW en-/decoder fixes) :/

**Comment by thopiekar** [comment]
Downgrading to B7 wouldn't be save, isn't it?

**Comment by JustArchi** [comment]
Fastest way - make TWRP backup, clean flash B7, test your issue, restore backup.

**Comment by thopiekar** [comment]
Ok, will even check B6 again, just to be sure.
Will have time for that tomorrow I think.

**Comment by thopiekar** [comment]
Made a fresh install from build 2015.04.xx to the current one and guess what Wifi Direct works!
And the best of all Miracast also works! Well, done! :heart: 

Just have to reinstall everything. I think there was something left on the install from CM12.0 or whatever :sweat_smile:

**Comment by JustArchi** [comment]
Alright then, so there is no bug in latest build :+1:
