### ISSUE TITLE
Google play store

### ISSUE THREAD

**Issue by boaz55** [ArchiDroid/android_device_samsung_i9300#123]
I get every minute an error about "Unfortunately, Google Play Store has stopped".
Is this related to rom or not ?
How to resolve this ?

**Comment by TwoD** [comment]
I got that too after flashing Build 9, it wouldn't let me sign in to my Google account either, complained about the service having issues.
I flashed the recommended GAPPS (Slim version) mentioned on http://forum.xda-developers.com/galaxy-s3/development/5-1-x-cyanogenmod-12-1-t3066864 and the problem went away.

**Comment by boaz55** [comment]
So do you suggest me that after flashing the: [5.1.1] [Build 9] [BETA] [2015-05-31] CyanogenMod 12.1 for i9300  - and check at aroma also install  "google service and play",
i install also the GAPPS : Slim_mini_gapps.BETA.5.1.build.0.x-20150526  from aroma ?
thanks !
Boaz

**Comment by TwoD** [comment]
I don't know what you mean by "aroma". I just flash both using CW or TWRP recovery from internal SD, nothing else.

**Comment by boaz55** [comment]
aroma = CWM
So you say flash the full : [5.1.1] [Build 9] [BETA] [2015-05-31] CyanogenMod 12.1 for i9300 
and after this install the: GAPPS : Slim_mini_gapps.BETA.5.1.build.0.x-20150526 
zip file ?

**Comment by TwoD** [comment]
Ah, ok. Yes.

**Comment by BLooDLorD** [comment]
i don't have any problems with play store or any GApps using Delta GApps from here
Clean installed build 9 and their's 5.1.1 base GApps.
http://forum.xda-developers.com/android/software/app-minimal-gapps-gapps-lp-20150107-1-t2997368

**Comment by boaz55** [comment]
THANKS
