### ISSUE TITLE
Camera not working at all and Snapchat not able to view videos.

### ISSUE THREAD

**Issue by 69ingchipmunkzz** [ArchiDroid/android_device_samsung_i9300#124]
Camera app (apk maybe) 

In snapchat I get the message "Snapchat was unable to open the camera. You may need to restart the app or device".. Restarting both does nothing.

GCamera gives message Cannot Connect to Camera

**Comment by 69ingchipmunkzz** [comment]
This is a very different issue to the other Camera Issue in the other thread, that issue consists of the camera freezing, mine does nothing but NOT open at all.

**Comment by JustArchi** [comment]
No, it's not. Camera issues are global.
