### ISSUE TITLE
No apps will display in Apps Drawer when UI Local is set to Hebrew

### ISSUE THREAD

**Issue by pcf1** [ArchiDroid/android_device_samsung_i9300#127]
Hello,

Here's a possible bug report for [Build 9] [BETA] [2015-05-31]:
ROM: cm-12.1-20150531-UNOFFICIAL-i9300-fixed.zip
Kernel: Your ROM's own Kernel.
TWRP: v2.8.6.1

Steps:
1. Performed a full wipe (via TWRP: Wipe → Advanced Wipe → Dalvik Cache + Cache + System + Data + Internal Storage).
2. Installed cm-12.1-20150531-UNOFFICIAL-i9300-fixed.zip
3. Installed Slim_mini_gapps.BETA.5.1.build.0.x-20150603.zip
4. Rebooted.
5. During the initial device's setup stages, I've selected [עברית] / Hebrew as my desired UI language.

Issues:
A. After step 5 and right before I was taken to the home screen, I got an [Unfortunately settings has stopped] error message.

B. For as long as the device's UI language is set to [עברית] / Hebrew, no apps will be displayed when clicking the Apps Drawer icon in the home screen (the circle with the 6 dots inside it):
http://imgur.com/a/kmsVj#2

The link above is a 3-screenshot album. On the rightmost screenshot, a couple of English letters can be seen and the rest are Hebrew letters. No app icons/names are present.

C. Once I set the device's UI language to [English (United States)], apps are being properly displayed:
http://imgur.com/a/5ogp6#0

D. None of the basic app names are listed in Hebrew, they are all listed in English even though during the initial device setup I've selected Hebrew.

On a side note, I've got a Samsung Galaxy S2 GT-I9100 running Lysergic Acid's CM 12.1 and all the UI/Language issues listed above are not exhibited there.

Many thanks for your ongoing support!

**Comment by pcf1** [comment]
Hello JustArchi,

Question please:
If the issue is not device-based, then how come the issue is non-existent on a Galaxy S2 GT-I9100?

Regards,

**Comment by JustArchi** [comment]
All of the issues you mentioned come directly from the android framework, which is not being considered.

I don't know why, it happens on device X rom X1 and why it doesn't happen on device Y rom Y1. I don't need to.

**Comment by pcf1** [comment]
Could you please point me in the right direction as to whom I should contact with this issue?

Regards,

**Comment by JustArchi** [comment]
CyanogenMod's JIRA.
