### ISSUE TITLE
Some bugs I found in 'cm-12.1-20150531-UNOFFICIAL-i9300-fixed'

### ISSUE THREAD

**Issue by tvdaXD** [ArchiDroid/android_device_samsung_i9300#129]
First of, I want to say this is absolutely great to have CyanogenMod 12.1 Thanks to you guys.
But here are some bugs:

1:The Flashlight turns off a second after the screen is turned off.

2: Some quick setting icons disappear or won't show after putting them in the quick settings menu. (Such as NFC)

3: When In Energy Saving mode, And I open a folder on the home screen, the screen goes a little darker like usual, but the icons won't appear. When I press back nothing happens and I am stuck on an empty screen. Only option is reboot.

4: This doesn't happen all the time, but sometimes I get the error: "Can't connect to the Camera."
This happens at random, maybe after using Snapchat or maybe after using the WhatsApp camera I don't know. To make it work again I need to reboot.

That's all for now, the rest works absolutely great!

**Comment by tvdaXD** [comment]
What do you mean with Not device-based? That all those bugs are on every device and still have to be fixed sometime?

**Comment by JustArchi** [comment]
1, 2, 3 -> I don't care, not device based, won't fix.
4 -> Duplicate

**Comment by tvdaXD** [comment]
Okay, I thought they were i9300 related.

**Comment by tvdaXD** [comment]
Does that mean they'll never be fixed?

**Comment by JustArchi** [comment]
No clue. They won't be fixed by me for sure.

**Comment by tvdaXD** [comment]
Alright, thanks. That's all I needed to know.
