### ISSUE TITLE
Cast Screen not working

### ISSUE THREAD

**Issue by justguesswho** [ArchiDroid/android_device_samsung_i9300#131]

**Comment by DimitriMayakovsky** [comment]
Yes i confirm this on nameless rom work's on cm12.1 no work maybe this is a issue of cm

**Comment by DimitriMayakovsky** [comment]
Archi you can reproduce if you have a smart tv

**Comment by DimitriMayakovsky** [comment]
Pick this maybe fix this shit cast

https://github.com/NamelessRom/android_frameworks_av/commit/261bfdd6cea5be61248642ae4590e3188d9f7614
