### ISSUE TITLE
Error during make of external_ffmpeg

### ISSUE THREAD

**Issue by frazzmark** [ArchiDroid/android_device_samsung_i9300#132]
I tried to compile myself the system, but since a couple of days it's failing at:
```
target asm: libavcodec <= external/ffmpeg/libavcodec/arm/hevcdsp_deblock_neon.S
external/stagefright-plugins/libstagefright/FFmpegExtractor/FFmpegExtractor.cpp: In member function 'android::sp<android::MetaData> android::FFmpegExtractor::setAudioFormat(AVStream*)':
external/stagefright-plugins/libstagefright/FFmpegExtractor/FFmpegExtractor.cpp:493:24: error: 'kKeyCodedSampleBits' was not declared in this scope
         meta->setInt32(kKeyCodedSampleBits, avctx->bits_per_coded_sample);
```
When i first merged ArchiDroid/android_device_samsung_i9300, the repo tool said it was ignoring some commits (from the CM base I think).
Since this problem breaks the build (the compiler stops here at this error) I think that if it was CM base- related it should be fixed in a couple of days. Every day I resynced the sources, but the error is still here, so I'm thinking it's device related.

**Comment by JustArchi** [comment]
Sources are synced when I'm about to compile the build, you can fork my sources and update yourself if you wish.
