### ISSUE TITLE
Online video streaming doesnt work and some small issues

### ISSUE THREAD

**Issue by omidhojjaty** [ArchiDroid/android_device_samsung_i9300#134]
online video streaming doesnt work with my browsers like chrome stock and opera. I tested it on galaxy s3 mini and it works on chrome. the problem is it really doesnt ask me to select any of video players!
also as soon as i change my simkart i should change setting hw overlay to play the videos and i cant seek back or forward.
I found a bug that camera dosnt work in some programs like barcod reader but it works in camera

**Comment by JustArchi** [comment]
Tested with internal browser and twitch.tv, everything works fine.

I'm not interested in closed-source third-party browsers.
