### ISSUE TITLE
Screen Flickering when battery is low

### ISSUE THREAD

**Issue by jon9066** [ArchiDroid/android_device_samsung_i9300#136]
When the battery percentage is about 20% or lower the screen flickers when the device performs tasks like swiping home screens or playing a game. White blurred lines flicker on screen and then the device freezes (and the lines disappear) requiring a hard reboot, or the device reboots itself. I have a few batteries so I think they aren't the issue, still I'd like to know it's not only me.

**Comment by JustArchi** [comment]
This is hardware issue related to dying battery. Replace your battery ASAP.
