### ISSUE TITLE
WIFI direct no working  and screencast

### ISSUE THREAD

**Issue by DimitriMayakovsky** [ArchiDroid/android_device_samsung_i9300#138]
https://github.com/NamelessRom/android_device_samsung_smdk4412-common/commit/631e6cbba11658ac8144e17523a7717c7c2dae31
https://github.com/NamelessRom/android_device_samsung_smdk4412-common/commit/c2d6a43cc7e731679bf478159a3c6b34f2054a04
https://github.com/NamelessRom/android_device_samsung_smdk4412-common/commit/11544e8d012baede275129ff8deb47df3608d33a
https://github.com/NamelessRom/android_device_samsung_smdk4412-common/commit/a9c4a36db4ecb52ca83f6de1c5ada7938a6396d1
https://github.com/NamelessRom/android_device_samsung_smdk4412-common/commit/2858e7272d6c81b4d8c41c7b10845387cfbc8e00

**Comment by DimitriMayakovsky** [comment]
https://github.com/NamelessRom/android_device_samsung_smdk4412-common/commit/2858e7272d6c81b4d8c41c7b10845387cfbc8e00

**Comment by DimitriMayakovsky** [comment]
https://github.com/NamelessRom/android_device_samsung_smdk4412-common/commit/a9c4a36db4ecb52ca83f6de1c5ada7938a6396d1

**Comment by DimitriMayakovsky** [comment]
https://github.com/NamelessRom/android_device_samsung_smdk4412-common/commit/11544e8d012baede275129ff8deb47df3608d33a

**Comment by DimitriMayakovsky** [comment]
https://github.com/NamelessRom/android_device_samsung_smdk4412-common/commit/c2d6a43cc7e731679bf478159a3c6b34f2054a04

**Comment by JustArchi** [comment]
Stop fucking spamming.

**Comment by JustArchi** [comment]
If you want to link me commits do a minimum and check if we don't have them already because you're acting as a blind guy linking everything left and right.

**Comment by JustArchi** [comment]
Out of your 5 commits we already had 4.

**Comment by DimitriMayakovsky** [comment]
I just noticed I'm sorry:>
