### ISSUE TITLE
Volume all high, but is low.

### ISSUE THREAD

**Issue by Manuz26** [ArchiDroid/android_device_samsung_i9300#142]
The overall volume of the device even if everything turned up .. is more lower than normal . I'm sure it's just because of this ROM on the other is not.

**Comment by nexuswolf** [comment]
The Volume decreases after A Phone Call Is placed

**Comment by nexuswolf** [comment]
Root/system/etc/sound/m0 is edited at headphones volume=63

When a call is placed/received the volume automatically decreases to the default 50 until the phone is rebooted
