### ISSUE TITLE
Fallout Shelter

### ISSUE THREAD

**Issue by simepy** [ArchiDroid/android_device_samsung_i9300#145]
Hi,

From build 16, Falllout Shelter quits just after the start game or a little later, not before witch build 15...

I think fallout out of memory

Log:

http://pastebin.com/BtpPXitm

Thank you in advance

**Comment by JustArchi** [comment]
I'm playing the same game and can't confirm this issue. Probably OOM.

**Comment by simepy** [comment]
What is the OOM ?

**Comment by JustArchi** [comment]
Google it.

**Comment by simepy** [comment]
Ok :) thanks, Are his may come from I have not made completely reinstall the ROM may just made the update ?

**Comment by JustArchi** [comment]
Yep.

**Comment by simepy** [comment]
OK, I'm try completely reinstall ROM,
Thanks you.

**Comment by simepy** [comment]
Hi, I'm sorry but Fallout Shelter quits just after the start game or later, after completely reinstall ROM and game...

try play game 20/30 minute or more. to test
