### ISSUE TITLE
Better charging screen

### ISSUE THREAD

**Issue by frazzmark** [ArchiDroid/android_device_samsung_i9300#146]
I noticed that flashing the CM12.1 also changes the charging screen displayed when you charge the phone while switched off. While I don't really mind if that isn't perfect, it would be nice that LED became green only on full battery, and stayed red while the battery is charging. The battery percentage is so small, sometimes I can't even read it because of the screen high brightness. Could any of this be improved?

**Comment by JustArchi** [comment]
LPM is now based on open-source (working!) implementation instead of proprietary crappy samsung one.

I'm not touching that sources myself, so I won't improve them as well.
