### ISSUE TITLE
Status LED too dark

### ISSUE THREAD

**Issue by pfannkuchengesicht** [ArchiDroid/android_device_samsung_i9300#147]
Installed CM12.1 build 16 on my GT-i9300 yesterday and noticed that the status LED is about half as bright as normal. When changing the settings for it(like color) it will switch to full brightness while in the settings dialogue. As soon as you leave that dialogue however, the brightness is reduced again.

**Comment by pfannkuchengesicht** [comment]
what? How is that not a bug?

**Comment by JustArchi** [comment]
CM uses lower LED brightness by default.

**Comment by pfannkuchengesicht** [comment]
but when I had CM10 it worked fine. Also why is the led brighter when changing the color setting?

**Comment by JustArchi** [comment]
Then switch to CM10.

**Comment by pfannkuchengesicht** [comment]
wow, what an attitude. Well thanks anyway.

**Comment by JustArchi** [comment]
You're welcome.

**Comment by orgua** [comment]
what Archi wanted to say: it's not kernel-specific anymore. So you have to change/mod your rom. OR you could try an adaptable kernel like the one from boeffla. It uses the same sources but has a special app to customize all these "special" things

**Comment by JustArchi** [comment]
It doesn't use the same sources. Source for my CM is AK, boeffla uses it's own adaptation based on KK sammy drop.

**Comment by pfannkuchengesicht** [comment]
Thank you, orgua!
