### ISSUE TITLE
Can't register an NFC trusted device in Smart Lock

### ISSUE THREAD

**Issue by MisterY** [ArchiDroid/android_device_samsung_i9300#15]
Steps to reproduce:
- Open Settings / Security / Smart Lock
- Go to Trusted Devices
- Add Trusted Device
- NFC
The screen opens, waiting for an NFC device is to be tapped.

At this point, Settings hang with the message "Google Play services isn't responding" coming up later.
Also, NFC control from the Quick Settings menu seems to lock-up.

NFC, however, works if activated on its own and NFC tags are tapped to the phone without using Smart Lock settings.

Whether framework or kernel-related, it might be useful to have this issue in case a workaround is found.
For me this is significant as it was probably the main reason to switch to Lollipop.

Note: I have Pico version of GApps flashed. But I'd expect Smart Lock, being a part of the system, to work even without GApps(?).

**Comment by JustArchi** [comment]
This is definitely not device-based issue, NFC works on kernel side.
