### ISSUE TITLE
FC : Settings -> Spell Checker -> Language

### ISSUE THREAD

**Issue by beshoo** [ArchiDroid/android_device_samsung_i9300#151]
Thank you for your hard work.. 
I dont know if it is just me. 
Igout a FC on Settings

Settings -> Spell Checker -> Language -> touch it !

catlog logs 

Code:
E/MessageQueue-JNI(16029): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.textservice.SpellCheckerInfo.getSubtypeCount()' on a null object reference
E/MessageQueue-JNI(16029):      at com.android.settings.inputmethod.SpellCheckersSettings.showChooseLanguageDialog(SpellCheckersSettings.java:170)
E/MessageQueue-JNI(16029):      at com.android.settings.inputmethod.SpellCheckersSettings.onPreferenceClick(SpellCheckersSettings.java:140)
E/MessageQueue-JNI(16029):      at android.preference.Preference.performClick(Preference.java:985)
E/MessageQueue-JNI(16029):      at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:214)
E/MessageQueue-JNI(16029):      at android.widget.AdapterView.performItemClick(AdapterView.java:305)
E/MessageQueue-JNI(16029):      at android.widget.AbsListView.performItemClick(AbsListView.java:1148)
E/MessageQueue-JNI(16029):      at android.widget.AbsListView$PerformClick.run(AbsListView.java:3059)
E/MessageQueue-JNI(16029):      at android.widget.AbsListView.onTouchUp(AbsListView.java:3878)
E/MessageQueue-JNI(16029):      at android.widget.AbsListView.onTouchEvent(AbsListView.java:3643)
E/MessageQueue-JNI(16029):      at android.view.View.dispatchTouchEvent(View.java:8480)
E/MessageQueue-JNI(16029):      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2400)
E/MessageQueue-JNI(16029):      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2093)
E/MessageQueue-JNI(16029):      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
E/MessageQueue-JNI(16029):      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
E/MessageQueue-JNI(16029):      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
E/MessageQueue-JNI(16029):      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
E/MessageQueue-JNI(16029):      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
E/MessageQueue-JNI(16029):      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
E/MessageQueue-JNI(16029):      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
E/MessageQueue-JNI(16029):      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
E/MessageQueue-JNI(16029):      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
E/MessageQueue-JNI(16029):      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
E/MessageQueue-JNI(16029):      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
E/MessageQueue-JNI(16029):      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
E/MessageQueue-JNI(16029):      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
E/MessageQueue-JNI(16029):      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
E/MessageQueue-JNI(16029):      at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2625)
E/MessageQueue-JNI(16029):      at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1770)
E/MessageQueue-JNI(16029):      at android.app.Activity.dispatchTouchEvent(Activity.java:2742)
E/MessageQueue-JNI(16029):      at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2586)
E/MessageQueue-JNI(16029):      at android.view.View.dispatchPointerEvent(View.java:8675)
E/MessageQueue-JNI(16029):      at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4129)
E/MessageQueue-JNI(16029):      at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3995)
E/MessageQueue-JNI(16029):      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
E/MessageQueue-JNI(16029):      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3603)
E/MessageQueue-JNI(16029):      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3569)
E/MessageQueue-JNI(16029):      at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3686)
E/MessageQueue-JNI(16029):      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3577)
E/MessageQueue-JNI(16029):      at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3743)
E/MessageQueue-JNI(16029):      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
E/MessageQueue-JNI(16029):      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3603)
E/MessageQueue-JNI(16029):      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3569)
E/MessageQueue-JNI(16029):      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3577)
E/MessageQueue-JNI(16029):      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
E/MessageQueue-JNI(16029):      at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5813)
E/MessageQueue-JNI(16029):      at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5787)
E/MessageQueue-JNI(16029):      at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5758)
E/MessageQueue-JNI(16029):      at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5903)
E/MessageQueue-JNI(16029):      at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
E/MessageQueue-JNI(16029):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/MessageQueue-JNI(16029):      at android.os.MessageQueue.next(MessageQueue.java:143)
E/MessageQueue-JNI(16029):      at android.os.Looper.loop(
E/AndroidRuntime(16029): FATAL EXCEPTION: main
E/AndroidRuntime(16029): Process: com.android.settings, PID: 16029
E/AndroidRuntime(16029): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.textservice.SpellCheckerInfo.getSubtypeCount()' on a null object reference
E/AndroidRuntime(16029):        at com.android.settings.inputmethod.SpellCheckersSettings.showChooseLanguageDialog(SpellCheckersSettings.java:170)
E/AndroidRuntime(16029):        at com.android.settings.inputmethod.SpellCheckersSettings.onPreferenceClick(SpellCheckersSettings.java:140)
E/AndroidRuntime(16029):        at android.preference.Preference.performClick(Preference.java:985)
E/AndroidRuntime(16029):        at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:214)
E/AndroidRuntime(16029):        at android.widget.AdapterView.performItemClick(AdapterView.java:305)
E/AndroidRuntime(16029):        at android.widget.AbsListView.performItemClick(AbsListView.java:1148)
E/AndroidRuntime(16029):        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3059)
E/AndroidRuntime(16029):        at android.widget.AbsListView.onTouchUp(AbsListView.java:3878)
E/AndroidRuntime(16029):        at android.widget.AbsListView.onTouchEvent(AbsListView.java:3643)
E/AndroidRuntime(16029):        at android.view.View.dispatchTouchEvent(View.java:8480)
E/AndroidRuntime(16029):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2400)
E/AndroidRuntime(16029):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2093)
E/AndroidRuntime(16029):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
E/AndroidRuntime(16029):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
E/AndroidRuntime(16029):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
E/AndroidRuntime(16029):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
E/AndroidRuntime(16029):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
E/AndroidRuntime(16029):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
E/AndroidRuntime(16029):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
E/AndroidRuntime(16029):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
E/AndroidRuntime(16029):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
E/AndroidRuntime(16029):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
E/AndroidRuntime(16029):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
E/AndroidRuntime(16029):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
E/AndroidRuntime(16029):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
E/AndroidRuntime(16029):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
E/AndroidRuntime(16029):        at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2625)
E/AndroidRuntime(16029):        at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1770)
E/AndroidRuntime(16029):        at android.app.Activity.dispatchTouchEvent(Activity.java:2742)
E/AndroidRuntime(16029):        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2586)
E/AndroidRuntime(16029):        at android.view.View.dispatchPointerEvent(View.java:8675)
E/AndroidRuntime(16029):        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4129)
E/AndroidRuntime(16029):        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3995)
E/AndroidRuntime(16029):        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
E/AndroidRuntime(16029):        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3603)
E/AndroidRuntime(16029):        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3569)
E/AndroidRuntime(16029):        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3686)
E/AndroidRuntime(16029):        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3577)
E/AndroidRuntime(16029):        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3743)
E/AndroidRuntime(16029):        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
E/AndroidRuntime(16029):        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3603)
E/AndroidRuntime(16029):        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3569)
E/AndroidRuntime(16029):        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3577)
E/AndroidRuntime(16029):        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
E/AndroidRuntime(16029):        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5813)
E/AndroidRuntime(16029):        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5787)
E/AndroidRuntime(16029):        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5758)
E/AndroidRuntime(16029):        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5903)
E/AndroidRuntime(16029):        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
E/AndroidRuntime(16029):        at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(16029):        at android.os.Messag
E/WifiService( 2416): Invoking mWifiStateMachine.setWifiEnabled
 mybeshoo
Yesterday, 4:33AM |#4167  
Senior MemberThanks: 7
 
When i connect mu GT-I9300 to my HOME charger , car mod start flicking in the screen !
a green Screen appear talking about car mode and a small icone appear in the left of the screen look like "car driver wheel"

How can i disable this !!

Please not that i did not enable any thing rated to this !
android.intent.category.CAR_DOCK
Here is the FULL catLog
http://pastebin.com/98p38ReC

Code:
I/ActivityManager( 2426): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.CAR_DOCK] flg=0x10200000 cmp=com.google.android.gms/.car.CarHomeActivity1} from uid 1000 on display 0
I/ActivityManager( 2426): Config changes=200 {1.0500001 417mcc1mnc en_US ?layoutDir sw360dp w360dp h615dp 320dpi nrml long port car finger -keyb/v/h -nav/h s.63 themeResource=themes:{default=overlay:system, iconPack:system, fontPkg:system, com.android.systemui=overlay:system, com.android.systemui.navbar=overlay:system}}
D/AkmSensor( 2426): MeasureSNGLoop: interval.interval = 66667000, doze_max = 65333, prms->enabled = 2
I/DockObserver( 2426): Dock state changed from 2 to 0
D/iNemoSensor( 2426): setDelay(): handle(0), en(200000000)
I/iNemoSensor( 2426): update_delay wanted_accel = 200000000
D/AkmSensor( 2426): MeasureSNGLoop: interval.interval = 200000000, doze_max = 196000, prms->enabled = 2
W/ContextImpl(11075): Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1723 android.content.ContextWrapper.startService:522 android.content.ContextWrapper.startService:522 com.android.settings.bluetooth.DockEventReceiver.beginStartingService:134 com.android.settings.bluetooth.DockEventReceiver.onReceive:78

I/ActivityManager( 2426): Config changes=200 {1.0500001 417mcc1mnc en_US ?layoutDir sw360dp w360dp h615dp 320dpi nrml long port finger -keyb/v/h -nav/h s.64 themeResource=themes:{default=overlay:system, iconPack:system, fontPkg:system, com.android.systemui=overlay:system, com.android.systemui.navbar=overlay:system}}
I/DockObserver( 2426): Dock state changed from 0 to 2
D/iNemoSensor( 2426): setDelay(): handle(0), en(66667000)
I/iNemoSensor( 2426): update_delay wanted_accel = 66667000
D/iNemoSensor( 2426): setDelay(): handle(0), en(66667000)
I/iNemoSensor( 2426): skip update_delay wanted_accel = 66667000 current delay = 66667000
I/ValidateNoPeople( 2426): skipping global notification
I/ActivityManager( 2426): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.CAR_DOCK] flg=0x10200000 cmp=com.google.android.gms/.car.CarHomeActivity1} from uid 1000 on display 0
I/ActivityManager( 2426): Config changes=200 {1.0500001 417mcc1mnc en_US ?layoutDir sw360dp w360dp h615dp 320dpi nrml long port car finger -keyb/v/h -nav/h s.65 themeResource=themes:{default=overlay:system, iconPack:system, fontPkg:system, com.android.systemui=overlay:system, com.android.systemui.navbar=overlay:system}}
D/AkmSensor( 2426): MeasureSNGLoop: interval.interval = 66667000, doze_max = 65333, prms->enabled = 2
D/GravityService( 5711): keeper SHAKE event
I/Choreographer( 2891): Skipped 36 frames!  The application may be doing too much work on its main thread.
I/ProviderInstaller(13905): Installed default security provider GmsCore_OpenSSL
D/GravityService

**Comment by beshoo** [comment]
Thanks for replying my case
Not device-based 
Is this mean CM Has this bug in any cm 12.1 so i need to report it to Cm.? 

Please advise

**Comment by JustArchi** [comment]
Yes, and most likely it's fixed already in updated sources.

**Comment by beshoo** [comment]
Thank you very much for yor kind reply, I don't know i have right to ask,  but what is your updated scale, i mean ( when,  what is your schedule) of updating CM Source code. Of your rom. 

Thank you in advance, honestly you made a wonderful work. Not a complement it is Fact.

**Comment by JustArchi** [comment]
Most likely next week.

**Comment by BambooIV** [comment]
bro,do we have android m for i9300

**Comment by beshoo** [comment]
@BambooIV please respect the offers and hard work @JustArchi did,  if he plans for that he will said for sure,  even Samsung did not say when it will provide M for six edg. 

And you ask for M for S3 our old very old phone. 

I am not sure about @JustArchi plans but he put a large effort for FREE.  To make u and me and other to see 5.1.1 number while other CM developer's let you down.  Even Samsung let you and me down. See in this point of view we have nothing to say but be humble and thankful four all time and hard work that @JustArchi did. 
He promised for an update next week....  Even Samsung did no dare  for such promises. 

Bottom of line.... Hear in github it is a plase to report bugs,  if you have no bug to report 
Go to xda and hit the thank you  button or ask for M.  In the xda. 


Sorry @JustArchi for any inconvenience.

**Comment by BambooIV** [comment]
@beshoo sorry man,I just wanna ask nothing more
and JustArchi is a great developer and very nice man and I like him sooooo much
may there any misunderstanding?all my bad
