### ISSUE TITLE
Hwc wrapper commits we need this ?

### ISSUE THREAD

**Issue by DimitriMayakovsky** [ArchiDroid/android_device_samsung_i9300#153]
https://github.com/ivanmeler/android_device_samsung_smdk4412-common/commit/fc9e14ab296f9f9cac691596f7dd75c73d47f454
https://github.com/ivanmeler/android_hardware_samsung/commit/8a49b791887d38b77c7a3cd17f14ef2a3973e845
https://github.com/ivanmeler/proprietary_vendor_samsung/commit/a77ffb564444781e731b307b3e2d64169884ff24

**Comment by JustArchi** [comment]
I don't care, CM is in EOL.

**Comment by DimitriMayakovsky** [comment]
Archidroid 3.1.5 eol ? :))

**Comment by JustArchi** [comment]
AD is based on latest CM sources which are EOL, and you're now submitting changes to CM sources.

**Comment by arter97** [comment]
Afaik that's still experimental.

**Comment by JustArchi** [comment]
To be exact, final version is being compiled right now. I no longer accept any patches/commits/changes to my CM sources, as they're EOL.
