### ISSUE TITLE
Android Keyboard (AOSP)-Gesture Typing not working.

### ISSUE THREAD

**Issue by glenv** [ArchiDroid/android_device_samsung_i9300#16]
Just downloaded Weekly2 and retested stock keyboard and gesture typing still not working. Can confirm that downloading and installing google keyboard works.

This was also occurring in Weekly1 release.

**Comment by dkuester** [comment]
Can confirm this.

**Comment by donrojo** [comment]
Can confirm this from Beta 6, Weekly 1, and Weekly 2. Swype Keyboard has work well in all three beta versions

**Comment by JustArchi** [comment]
Not device-based issue.
