### ISSUE TITLE
System Profiles Glitches

### ISSUE THREAD

**Issue by donrojo** [ArchiDroid/android_device_samsung_i9300#19]
Since Beta 6, every time I set profile to Silent (a star shows on the notification bar. When I decide to change the profile, say Default or Indoor or other personalised presets the star does not move. I have to select once again Silent Profile (the star turn into "stop" sign - cicle with a diagonal diameter line. Then select another profile of choice to have the last icon removed from the notification bar.
Also, I have not been able to verify if it is related, but quite often (Beta 6, Weekly1) I have noticed that my ringtone and notification sound returns to default, although I have set every profile so that these two tunes are not changed. I just flashed Weekly 2 and need still some time to see if this issue is gone or still present

**Comment by JustArchi** [comment]
Not device-based issue.
