### ISSUE TITLE
Mount and unmount external sd

### ISSUE THREAD

**Issue by DimitriMayakovsky** [ArchiDroid/android_device_samsung_i9300#21]
As it removes the sdcard and put back you need to restart the device

**Comment by MarcKe** [comment]
Cannot replicate. I used the option to unmount and mount the sd card in Settings/Storage and it worked fine.

**Comment by DimitriMayakovsky** [comment]
For the 1st time work but then you have to start again

**Comment by DimitriMayakovsky** [comment]
It just does not work as it removes the card from the slot sd

**Comment by DimitriMayakovsky** [comment]
This is the same as it removes otg pendrive need to restart the device and then use it again

**Comment by sunny1234590** [comment]
It's working for me tried 8-9 times to mount and unmount.

**Comment by DimitriMayakovsky** [comment]
Remove card from sdcard slot and try....

**Comment by JustArchi** [comment]
You're not supposed to remove card from sd slot.

**Comment by JustArchi** [comment]
This is the whole purpose of noemulatedsd added in fstab some time ago by me

**Comment by DimitriMayakovsky** [comment]
Before you added it was the same on otg and sdcard

**Comment by JustArchi** [comment]
I'll check it myself soon, then mark it as confirmed or can't reproduce.

**Comment by DimitriMayakovsky** [comment]
https://jira.cyanogenmod.org/browse/CYAN-6293?jql=project%20%3D%20CYAN%20AND%20resolution%20%3D%20Unresolved%20AND%20priority%20%3D%20Normal%20ORDER%20BY%20key%20DESC

**Comment by DimitriMayakovsky** [comment]
02-05 14:03:57.763 D/DirectVolume(1920): DirectVolume::handlePartitionAdded -> MAJOR 179, MINOR 17, PARTN 1 in logcat

**Comment by stickman89** [comment]
Also experiencing this issue, with both internal SD card and OTG flash drives (OTG flash drives do not even have a 'safely remove' prompt within notification tray). Device needs to be rebooted in order for removed/reinserted storage to be detected...

**Comment by kcambridge** [comment]
Experiencing the same issue. SD Card continuously shown as unmounted. Removing physically and or restarting device has no effect.

**Comment by DimitriMayakovsky** [comment]
https://github.com/CyanogenMod/android_frameworks_base/commit/9d0514d80f9a664d5fcda0c0f870229f35afa9b1

**Comment by DimitriMayakovsky** [comment]
Problem has been solved on the latest weekly 5  :+1:
