### ISSUE TITLE
In-Call Noise reduction not working

### ISSUE THREAD

**Issue by PradeepBolt** [ArchiDroid/android_device_samsung_i9300#22]
Background noise is not getting suppressed. I face this issue with many S3 Kitkat and lollipop roms. I use stock kernel. Please check out. I love your work ! Thank you !

**Comment by MarcKe** [comment]
That feature has not been ported to cm12 yet (talking about the settings in the rom).
So, its not activated on our device atm. If they wont do it, we can maybe activate it by default.

**Comment by CyberianIce** [comment]
It should be implemented by now in CM12 sources, there is option in dialer settings but need to be tested.

**Comment by MarcKe** [comment]
This is not ready yet. It was also not implemented by cm, but me.

**Comment by MarcKe** [comment]
Should be working now.
