### ISSUE TITLE
Ambient Display visible for just 3 seconds

### ISSUE THREAD

**Issue by disidisruptor** [ArchiDroid/android_device_samsung_i9300#24]
If "Ambient Display" is enables (Settings -> Display -> Ambient Display) incoming notifications are just visible for about 3 seconds on the ambient display. That's a bit short isn't it :D!?

**Comment by sunny1234590** [comment]
It is working for me. The ambient display appears again when you pick you phone up. 
This is how it works.

**Comment by JustArchi** [comment]
Anyway, not device-based.
