### ISSUE TITLE
Volume gets distorted when using headphones and getting a notification  

### ISSUE THREAD

**Issue by charliehorseuk** [ArchiDroid/android_device_samsung_i9300#32]
With headphones, if listening music, and receiveing a notify, the audio mixer gets crazy, the volume of the channel of the music gets super high (incredibly high) and music is distorted till I do a simple volume up or down or pause and unpause.

**Comment by MarcKe** [comment]
This is actually a cm issue. Ive seen lots of patches in cm lately. Might be fixed in the next release.

**Comment by Haringstad** [comment]
I can confirm this too. (The issue)

**Comment by MarcKe** [comment]
I cannot reproduce it on latest builds.
