### ISSUE TITLE
No OTG mouse cursor/pointer - Invisible Pointer

### ISSUE THREAD

**Issue by stickman89** [ArchiDroid/android_device_samsung_i9300#37]
Reporting bug - Mouse cursor/pointer is not visible when using a mouse via OTG cable. Mouse is functioning, just very difficult to use without a pointer.

**Comment by DimitriMayakovsky** [comment]
This is maybe cm issue

**Comment by stickman89** [comment]
More than likely. Folks may have missed my reporting post on XDA, so thought I'd make a placement for it here. Haven't got another device to confirm, nor could I find any reports elsewhere. If someone could confirm a CM issue, I'd be happy to report it to the relevant area.

**Comment by JustArchi** [comment]
CM bug.
