### ISSUE TITLE
WiFi direct don't work

### ISSUE THREAD

**Issue by DimitriMayakovsky** [ArchiDroid/android_device_samsung_i9300#40]
Maybe missing this https://github.com/DimitriMayakovsky/android_device_samsung_i9300/commit/a3c1679f34c6d34976be2771b9b6a0b350276ff5

**Comment by DimitriMayakovsky** [comment]
Okay i found fix :] use the app superbeam

**Comment by MarcKe** [comment]
Ye, it also makes no sense. Those files are already in smdk4412-common.
I personally dont have any device to test. So I cannot really help.
