### ISSUE TITLE
kswapd0 eating tons of CPU time

### ISSUE THREAD

**Issue by ForsakenNGS** [ArchiDroid/android_device_samsung_i9300#41]
I have some serious trouble since some time (say a week). My device started getting slow and laggy. Having really long load times and sometimes having "Not enought memory" errors when installing an app e.g. (even I have more than 1gb free on both internal memory and sdcard)
In the shell I observed "kswapd0" to use 50-95% (!!!) of the CPU power. Is there maybe some Issue of the swap or ram not beeing cleaned up properly? I'll try to make a reset as soon as I can in order to hopefully solve this problem that way and post the result here.

**Comment by MarcKe** [comment]
Use free in shell and show the results.
Also show what you see in /sys/block/vnswap0/vnswap_init and vnswap_swap_info
Might be that being full is not handled correctly.
Maybe we should switch to zram again. Vnswap/zswap might be buggy

**Comment by JustArchi** [comment]
This is directly connected with vnswap enabled by MarcKe some time ago.

We must find better solution. Having more memory is crucial, but we can't spend too much time on compressing/decompressing pages, it must be fast as hell, something with LZO or LZ4 algorithm.

**Comment by JustArchi** [comment]
I'll try to find better way when I'm done with the new ArchiKernel. This will help a lot. We could use Samsung's solution from stocks.

**Comment by MarcKe** [comment]
I will simply try zram with lz4 and push out a test build :P

**Comment by MarcKe** [comment]
Shouldnt happen anymore in next nightly/weekly with zram, unless the same bug also exists there which I dont believe.
