### ISSUE TITLE
SDCard was obviously completely deleted! (As well as emulated sdcard on internal)

### ISSUE THREAD

**Issue by ForsakenNGS** [ArchiDroid/android_device_samsung_i9300#46]
Hi there, in order to test the fix of #41 I wanted to apply the newest nightly build. Since I was somewhat low on free space I decided to cleanup some old files before and did so. After that I copied the newest nightly to my phones sdcard and rebooted into recovery mode.
When trying to install the zip file I didnt see any files or folders on the sdcard. There only was a "Android" and "LOST.DIR" folder. Booting back into android (without installing or doing anything further) i noticed ALL of my sdcard data was simply gone. The external as well as the internal, everything is just deleted. No "SDCard Error" or something, it looks loke the ROM just decided to format it and use the then empty sdcard(s) again. How is such a thing even possible?!
Is there any chance I might get at least some of my data back? I gladly moved all of my camera's pictures to my laptop while cleaning up, but there's still tonns of stuff that I only have outdated or even no backups of anymore.

$ df
/mnt/shell/emulated     11.4G     7.3G     4.1G   4096
/storage/emulated      417.4M     0.0K   417.4M   4096
/mnt/media_rw/sdcard1    29.3G   864.0K    29.3G   32768
/mnt/secure/asec        29.3G   864.0K    29.3G   32768
/storage/sdcard1        29.3G   864.0K    29.3G   32768
/storage/emulated/0     11.4G     7.3G     4.1G   4096
/storage/emulated/0/Android/obb    11.4G     7.3G     4.1G   4096
/storage/emulated/legacy    11.4G     7.3G     4.1G   4096
/storage/emulated/legacy/Android/obb    11.4G     7.3G     4.1G   4096

Before the sdcard was like 25G of the 29.3G used...

**Comment by NoTengoBattery** [comment]
If you SDCard is formatted as FAT (it generally does), you can try to use a data recocery tool that support FAT (like Recuva or other). During a "fast" formatting, the disk is not "fully erased", instead, the superblock is washed out but the files still there unless some other file overwrite it physically. If a "slow formatting" happend, the files (the whole memory) was overwritten and the files may not exist physically any more. Sorry, bad English ;) good luck

**Comment by MarcKe** [comment]
Sorry, but this is not a device issue. Open a thread in the help section on xda.
