### ISSUE TITLE
NFC Quick settings tile not showing up

### ISSUE THREAD

**Issue by joen93** [ArchiDroid/android_device_samsung_i9300#52]
I'm not sure if this is a CM12 issue or a rom issue, but here's the thing.

I tried to add the NFC tile to my quick settings. Problem is, no matter where I put the tile, it won't show up among my quick settings. It's somehow ignored, like it isn't even there, any tile that should show after the NFC tile kinda 'overwrites it'.

**Comment by MarcKe** [comment]
This also happens on other devices, not device related.
