### ISSUE TITLE
Broken MMSes

### ISSUE THREAD

**Issue by JustArchi** [ArchiDroid/android_device_samsung_i9300#54]
Receiving MMSes doesn't work despite proper APNs.

Low prio, when it's time for that.

**Comment by dominiq0** [comment]
I had this same issue. After rebooting  system MMS was finally download.  Sometimes i recieve mms normally sometimes i must reboot phone and wait a moment.

**Comment by JustArchi** [comment]
Fixed in https://github.com/ArchiDroid/proprietary_vendor_samsung/commit/0f7c3d0ba39c22baa32299e37d82de9220c819e3

TODO: Check if we still need long SMSes workaround in Exynos4RIL.java

**Comment by MarcKe** [comment]
And data still works after replacing the modified libsec-ril?

**Comment by JustArchi** [comment]
Of course it does, why shouldn't it?

**Comment by MarcKe** [comment]
Because it was modified to make data work on lollipop.
https://github.com/ArchiDroid/proprietary_vendor_samsung/commit/60801bc9923d1c14900cc40bb3fdb4f1881d6a47

**Comment by JustArchi** [comment]
And I said back then that we shouldn't modify blobs as it shouldn't be needed. Do you remember that? :+1:

**Comment by MarcKe** [comment]
Ye, but it was needed. The fix in hardware_samsung wasnt any better.

**Comment by JustArchi** [comment]
It wasn't, our reverse engineered RIL was the problem, not the blob that communicated with the modem. Now it's OK.

**Comment by JustArchi** [comment]
Also, now CM actually started caring about that RIL (they merged them together a few days ago in hardware_samsung) so we should keep blobs as recent as possible, without modifying them.

**Comment by JustArchi** [comment]
i9300 part is done - GPS, sensors and RIL blobs are up-to-date, and smdk4412 is my next step when I get some time.

**Comment by JustArchi** [comment]
I'm just wondering why we override sensors with proprietary blobs if we have reverse engineered sensors from Replicant, this is making me curious so I'll check that soon.
