### ISSUE TITLE
My voice is very low in voice calls

### ISSUE THREAD

**Issue by Saeed-Pooyanfar** [ArchiDroid/android_device_samsung_i9300#56]
I have the latest version (W7) ...
My voice is extremely low in voice calls!
I don't know it's a hardware or software problem!?!

**Comment by Saeed-Pooyanfar** [comment]
I don't have this problem in social apps like viber ...
So it's a software problem!

**Comment by DimitriMayakovsky** [comment]
Cm bug

**Comment by Saeed-Pooyanfar** [comment]
I hope this critical problem will fix soon because it's very annoying for me! (and probably for others!)

**Comment by charliehorseuk** [comment]
Had this problem as well turned off noise suppression in dialer settings fixed the problem for me

**Comment by Saeed-Pooyanfar** [comment]
@charliehorseuk : Thanks ... it became better but i think it must be louder!

**Comment by pixelfehler1996** [comment]
I had the same problem. Then I installed an original Samsung ROM and installed back to this ROM. Now it works for me.
