### ISSUE TITLE
Spirit UL not working

### ISSUE THREAD

**Issue by DineshPatil3** [ArchiDroid/android_device_samsung_i9300#57]
After the update of CM12 weekly 5 the Spirt UL application is not working.
It gives an error as follows:
Error: No FM accessible
SU: 2 Fm:SLS Su:1 Bt:0 Ht:0 Mo:SLS

I've already enabled root access and its still not working.
The issue remains same for weekly 6 & 7 as well.

**Comment by MarcKe** [comment]
This is not going to be considered here.

**Comment by DineshPatil3** [comment]
Thanks for the support. I've got it resolved by updating the software.
