### ISSUE TITLE
duplicate images show in the gallery

### ISSUE THREAD

**Issue by poploock** [ArchiDroid/android_device_samsung_i9300#60]
Hi, I have images in the gallery to display each 3 times and only the first image opens and other displays blank image.

**Comment by poploock** [comment]
![screenshot_2015-03-11-16-11-32](https://cloud.githubusercontent.com/assets/8267607/6596416/6cdc7c64-c809-11e4-84b2-ad54861e1c50.png)
Samsung Galaxy S III I9300

**Comment by DineshPatil3** [comment]
Should reopen this issue. As I've only 200 images in a folder but Gallery shows 1200 images in that folder. Kindly re-open this is a bug.

**Comment by MarcKe** [comment]
No.

**Comment by JustArchi** [comment]
Which part of "we're not fixing not device-based bugs" you didn't understand?

This issue is caused by either CM, or AOSP, in both cases we don't care. Submit your bug to CM's JIRA or AOSP's bugtracker.
