### ISSUE TITLE
Speaker does not work after earphones are unplugged

### ISSUE THREAD

**Issue by DineshPatil3** [ArchiDroid/android_device_samsung_i9300#61]
I've experienced a bug where my Speaker don't give any output after unplugging earphones from my Samsung Galaxy S3 phone. I've tried several options and found that the sound works only if I change the alarm tone. This is a serious problem as after unplugging the earphones, I missed many calls as the phone speakers was not working and no ringtone was audible.

**Comment by MarcKe** [comment]
Does not happen here on weekly 8.

**Comment by DineshPatil3** [comment]
Thanks for the support, the issue has been resolved in Weekly 8. You rock :+1:
