### ISSUE TITLE
Video streaming issue

### ISSUE THREAD

**Issue by PetarVlad** [ArchiDroid/android_device_samsung_i9300#63]
When playing a video stream from the built-in video player(eg. Youtube video launched via browser), the video freezes if you move the progress bar, while the audio jumps and continues without any problem. Changing between Awesome player and NuPlayer has no effect.

**Comment by MarcKe** [comment]
Cannot confirm this. Archi, what about you?

**Comment by JustArchi** [comment]
http://i.imgur.com/p4BiZ5A.png

Tried, can't reproduce either.

**Comment by PetarVlad** [comment]
It seems to be a per-browser issue. The playback works fine in the default android browser and CM Browser. It has the mentioned behavior in UC Mini. In chrome this is how the video is rendered: http://i.imgur.com/AR72tD3.png

**Comment by MarcKe** [comment]
Chrome is annoying. It causes problems with rendering, videos and probably even more...

**Comment by JustArchi** [comment]
If it works fine in CM browser, then we simply "don't care". We can't check what is wrong with third-party closed-sourced apps.

**Comment by JustArchi** [comment]
Also, your screen looks very similar to new nuplayer issue.

**Comment by PetarVlad** [comment]
The picture was taken using awesome player. The problem persists in nuplayer too. I thought since multiple browsers have problems with video playback, that it "should" be a system or device issue. Since it plays streams normally in selected browsers, i am confused. Especially since everything it worked fine a few weeks ago.

**Comment by JustArchi** [comment]
Some of the codecs are in fact handled by hwcomposer and resist on device-side, but if we can't reproduce the issue in open-sourced browser, then you can't expect us to fix closed source apps and their quirks.

**Comment by PetarVlad** [comment]
I guess i can either downgrade to an older build/system or wait for app updates. Thanks for the replies anyway guys. Keep up the good work.
