### ISSUE TITLE
Incall Audio Feeble

### ISSUE THREAD

**Issue by ajaymath** [ArchiDroid/android_device_samsung_i9300#64]
I know there seems to be another one reported but I have no data turned on so I don't suppose its the same issue. Speaker phone works fine though.Clean install didn't fix it.  I'm sorry I couldn't catch a log , have you two ever come across this issue?

**Comment by MarcKe** [comment]
What does feeble mean for you?

**Comment by PetarVlad** [comment]
feeble
adjective
lacking in volume, loudness, brightness, distinctness, etc.:
a feeble voice; feeble light.

**Comment by ajaymath** [comment]
thank you Petar. and yes, I can't say there is no audio nor can I say the
audio is distorted, The volume is extremely low, as if the voice is being
suppressed.

Running stock kernel, weekly 8.

**Comment by wsisback** [comment]
any developments on this issue? I have the same problem.

**Comment by JustArchi** [comment]
Duplicate of https://github.com/ArchiDroid/android_device_samsung_i9300/issues/20, or can't reproduce if it's not that issue.

**Comment by vnikolaenko** [comment]
I have same problem.

**Comment by ajaymath** [comment]
If its any help to any of you, I used Boeffla Kernel Sound to increase me
incall speaker and its quite alright now.
