### ISSUE TITLE
No GPS Signal in Google Maps for example

### ISSUE THREAD

**Issue by Hardstyl3R** [ArchiDroid/android_device_samsung_i9300#65]
I have an unpleasant issue with the GPS Signal on my device. I use my galaxy often for navigation an till the update to your cyanogenmod everything works fine.
But yesterday i got ongoing the message that there is "no gps signal" although i activate "high accuracy" in the gps settings.
It seems that there is an issue with a gps signal what is continuous needed and not for just one moment.
Do you confirm that issue?

**Comment by JustArchi** [comment]
Already fixed IIRC.
