### ISSUE TITLE
Hardware decoder/encoder issues

### ISSUE THREAD

**Issue by ng1998** [ArchiDroid/android_device_samsung_i9300#66]
facebook videos play normally but when u skip forward or backward the video freezes but audio continues

**Comment by mfonville** [comment]
This is not limited to the Facebook app. It also happens in other applications that use video, like the app from the Dutch public broadcasting service (NOS.nl).

**Comment by LittleHuba** [comment]
Found the issue lays in the use of the decoder. When a player uses the hardware decoder it will stop playback. When you use software decoder it will continue after some time. Seams like the hardware decoder simply won't restart the playback.

**Comment by JustArchi** [comment]
Also http://forum.xda-developers.com/showpost.php?p=60219201&postcount=837

**Comment by JustArchi** [comment]
Re-evaluate this in build 8 please.

**Comment by ibhh** [comment]
I have also issues with build 8. (VLC player, Dirty flash)

**Comment by mfonville** [comment]
I flashed build 8, but playback is still broken (at least in the NOS.nl app). Only a black screen.
I will go back to build 7, because of the related camera problems. But thank you for putting the effort in such a big overhaul of the sources, trying to get it all working :-)

**Comment by JustArchi** [comment]
Re-evaluate this in build 9 please.

(Including netflix which I hopefully fixed)

**Comment by JustArchi** [comment]
Fixed everything apart from netflix.

**Comment by mfonville** [comment]
Yes, it is fixed in build 9 :-)
