### ISSUE TITLE
Battery Saver Mode - Auto Restart

### ISSUE THREAD

**Issue by alimerdan** [ArchiDroid/android_device_samsung_i9300#67]
First of all i would like to thank you guys for the great effort which is highly appreciated, more than you imagine :)
I found the following issue:
Settings->Notification drawer->Select and order tiles (contains in order):
Wi-Fi, Data Connection,
Bluetooth, Rotation, Flashlight,
Location, Hotspot, Battery mode.

When toggle battery mode (while charging the mobile) to "Power save" mode, the mobile auto restart.

it also happens (occasionally) if the charger is not connected.

**Comment by JustArchi** [comment]
What restart is that?

If soft reboot - not device based.
If hard reboot - kernel.

**Comment by alimerdan** [comment]
Hard reboot.
my kernel version is:
3.0.31-CM-ge5e205a
bob@bob-system-Product-Name #1
Mon Mar 16 14:13:50 CET 2015

**Comment by LittleHuba** [comment]
Can confirm this issue.

kernel version:
3.0.31-CM-g8396719
arter97@arter97-Haswell #1 
Thu Feb 26 00:13:43 KST 2015

**Comment by luhrmanm** [comment]
Same issue here, hard reboot.

kernel version:
3.0.31-CM-ga8355e7b
bob@bob-system-Product-Name #1
Mon Mar 23 20:04:20 CET 2015

**Comment by JustArchi** [comment]
Can't reproduce anymore on latest CM12.1.
