### ISSUE TITLE
Does not discontinue charging when the battery is full.

### ISSUE THREAD

**Issue by DineshPatil3** [ArchiDroid/android_device_samsung_i9300#68]
Hi there,
I'm not sure if I'm logging this at the right place, i.e. this is related to the CM12 issue or something else. But I've observed that the charger doesn't discontinue charging when the battery is full. This was mainly observed while using power bank, it works with my other Galaxy S3 where it gives an alert that "the charging is full, please remove the charger." When such alert comes, my power bank turns off on its own. But this is not the case with my Galaxy S3 with CM12 installed, it keeps on charging, never gives an alert to remove the charger, nor my Power Bank gets off. Same is observed with the regular Samsung Original charger. Really appreciate if you can have a look at this.

**Comment by JustArchi** [comment]
Not sure if we can fix anything here. The kernel is responsible for that, and we even updated sources to N7100, just to make sure that we can go as far in compatibility as we can get.

Maybe @MarcKe will come with the solution, but I can't think of any.

**Comment by MarcKe** [comment]
Did it work on cm11?

**Comment by JustArchi** [comment]
I MAY have a clue where the bug comes from, but yeah you must firstly let us know if CM11 works properly.

**Comment by DineshPatil3** [comment]
Not sure if it was working on CM11 or not. Will have to install it and test it.

**Comment by JustArchi** [comment]
I checked what I could (charging) and kernel properly handles scenario when battery is full, on AC and USB.

Can't check power banks tho.
