### ISSUE TITLE
Misc SELinux deny

### ISSUE THREAD

**Issue by JustArchi** [ArchiDroid/android_device_samsung_i9300#69]
<4>[   13.705411] c3 type=1400 audit(1427307108.670:270): avc: denied { read } f
or pid=2767 comm="system_server" name="prox_cal" dev=mmcblk0p3 ino=58 scontext=u
:r:system_server:s0 tcontext=u:object_r:efs_file:s0 tclass=file

**Comment by JustArchi** [comment]
prox_cal is responsible for proximity calibration.

**Comment by JustArchi** [comment]
3 more.

<4>[  152.719676] c1 type=1400 audit(1427330675.617:207): avc: denied { create } for pid=5065 comm="gpsd" name="baro.dat" scontext=u:r:gpsd:s0 tcontext=u:object_r:system_data_file:s0 tclass=file
<4>[  169.268018] c1 type=1400 audit(1427330692.167:208): avc: denied { create } for pid=1963 comm="gpsd" name="gldata.sto" scontext=u:r:gpsd:s0 tcontext=u:object_r:system_data_file:s0 tclass=file
<4>[  169.284635] c1 type=1400 audit(1427330692.182:209): avc: denied { create } for pid=5065 comm="gpsd" name="baro.dat" scontext=u:r:gpsd:s0 tcontext=u:object_r:system_data_file:s0 tclass=file

**Comment by MarcKe** [comment]
2nd one is easy to fix. 1st one most likely needs some more handling, since I dont want to give gpsd general access to the efs_file context.

**Comment by MarcKe** [comment]
Btw, gonna fix the other one when I have more time (next week)

**Comment by JustArchi** [comment]
:+1:

**Comment by JustArchi** [comment]
The only two left are these:

```
<4>[   11.285361] c1 type=1400 audit(1427683716.335:125): avc: denied { read } for pid=2813 comm="system_server" name="prox_cal" dev=mmcblk0p3 ino=58 scontext=u:r:system_server:s0 tcontext=u:object_r:efs_file:s0 tclass=file
<4>[   11.285668] c1 type=1400 audit(1427683716.335:125): avc: denied { open } for pid=2813 comm="system_server" name="prox_cal" dev=mmcblk0p3 ino=58 scontext=u:r:system_server:s0 tcontext=u:object_r:efs_file:s0 tclass=file
```

**Comment by MarcKe** [comment]
When do you get them actually? Ive never seen them before. I want to know how to replicate

**Comment by JustArchi** [comment]
Hard to say, I'm noticing them right after boot, through `dmesg | grep avc`.

Probably some early system service.

**Comment by JustArchi** [comment]
With new open-source sensors this issue is gone.

Probably closed source sensors have some calibration task on init.

Either way, obsolete thing to do.

**Comment by JustArchi** [comment]
Or apparently it's still there.
```<36>[  189.302178] c3 type=1400 audit(1436508955.599:240): avc: denied { read } for pid=2455 comm="PowerManagerSer" name="prox_cal" dev=mmcblk0p3 ino=58 scontext=u:r:system_server:s0 tcontext=u:object_r:efs_file:s0 tclass=file```

**Comment by JustArchi** [comment]
Fixed in https://github.com/ArchiDroid/android_device_samsung_i9300/commit/a244a47571e1b5333cfeb8edc5f10452538808d4
