### ISSUE TITLE
Snapchat records only ~2 seconds

### ISSUE THREAD

**Issue by JustArchi** [ArchiDroid/android_device_samsung_i9300#7]
Things to check:
- If it works fine with camera wrapper

**Comment by szotaa** [comment]
i9300 has this issue since cm 10.2. Didn't test on earlier versions. On stock 4.3 ofc it works fine

**Comment by MarcKe** [comment]
Going to quote ricardo cerqueira: "App issue, unfortunately. Snapchat requests 2 limits on recordings: 10 seconds, and 900Kbytes, whichever comes first. The media profiles on the i9300 (12mbps video + 128kbps audio) reach 900K in about 5 seconds, so we can't quite fix this without lowering the recording quality"

**Comment by JustArchi** [comment]
Key-thing -> it works on stock.

Can't see check media profiles on stock then?

**Comment by MarcKe** [comment]
Actually they even increased the size limit, its like 1.6mb, but currently our s3 reaches this after 2 seconds. I doubt you will find much in media profiles on stock, but go ahead.
