### ISSUE TITLE
Settings application crash

### ISSUE THREAD

**Issue by UngarMax** [ArchiDroid/android_device_samsung_i9300#76]
In first place, thanks to all developers that contributed to the creation of this awesome ROM that brings Android 5 to Samung Galaxy SIII.

Alright, lets get to the point now: I found a bug which causes the Settings application to crash. This can be reproduced by going to Settings and pressing Mobile data (not actually toggling the status but accessing its settings).

Kernel version:
3.0.31-ArchiKernel-CM-gd13f4d1
root@ArchiDroid #1
Mon Apr 6 23:38:04 CEST 2015

**Comment by UngarMax** [comment]
What's "Not device-based" supposed to mean?

**Comment by JustArchi** [comment]
It means that I don't care about your bug, as it should be fixed by CM.

And we're not answering questions about ROM here. This issue is closed.
