### ISSUE TITLE
Issue: debugging confirmation keeps appearing

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [ArchiDroid/android_device_samsung_i9300#78]
Even if I choose to remember it.
Each time I connect the device to the PC (via USB or via Wifi), it asks if I allow it to be able to debug. When I choose that I allow (and choose to remember it), it will work only for a limited time (could be an hour, could be some minutes), or till the next time I connect the device to the PC.
I'm talking about this dialog (found via the Internet) :
http://4.bp.blogspot.com/-kYKWJ_9TjEo/USN-vQqpUPI/AAAAAAAAL3M/xozI-9JuLDM/s1600/adb-debug-confirmation.png

Please fix this. I've noticed this issue on many (or all?) Android 5.1 based roms for I9300, even on OmniRom based ones.
I think it also happened on Android 5.0 based roms too.

it might be related, but I think the Wifi sometimes gets shut down when the device goes to sleep (after a while). This also mean that it needs to re-connect each time I wake it up, so I need to wait before I run an app that needs an Internet connection.
Or, at least, the OS loses the Wifi connection via ADB. I'm really not sure what causes it and what exactly is the issue in this case.

Speaking of Android development issues, I've also found out that this log keeps being written:
04-09 10:08:11.400 1936-31987/? E/SECHWC_LOG﹕ int g2d_handle_oneshot_capture(hwc_context_t*)::Fail to get SECMEM info
04-09 10:08:11.400 1936-31987/? E/SECHWC_LOG﹕ g2d_handle_oneshot_capture fail

I don't think it's related to the issue, but that's just a guess and might help.

**Comment by AndroidDeveloperLB** [comment]
Why no fix? Non of those are related to I9300 ? and there is no way to fix it on CM itself?

:(

**Comment by AndroidDeveloperLB** [comment]
Now I've found out the version "12.1-20150406" actually doesn't have the debug confirmation issue, but it existed before.

**Comment by JustArchi** [comment]
So you don't only report issues that we don't care about, but you also don't report issues that even exist in the latest version, well done :+1:

**Comment by AndroidDeveloperLB** [comment]
@JustArchi It wasn't on purpose. I've tested multiple roms recently, and decided to report about this issue after I've found out it's a common issue.  It really annoyed me for quite some time and I have reported about it on XDA too. Here I've reported only yesterday.
Please don't be mad. I'm sorry. 
If you don't believe me, I can email you a video showing the issue occurring .
