### ISSUE TITLE
WiFi disconnects in deep sleep

### ISSUE THREAD

**Issue by JustArchi** [ArchiDroid/android_device_samsung_i9300#9]
WiFi disconnects if phone is deep sleeping for some time, even if it's set to never disconnect

**Comment by vishnu9009** [comment]
Due to this bug only i haven't flashed this rom yet. Hopefully this will be fixed soon

**Comment by makiftasova** [comment]
I am affected by this one too (at least for 22.01.2015 build, just updated to 29.01.2015 build and waiting for boot)

**Comment by Guido-glx** [comment]
I'm also affected. Bug is still here, on weekly 2.1

**Comment by szotaa** [comment]
Never happens with boeffla kernel. Maybe he is the right person to ask

**Comment by Guido-glx** [comment]
This has been post on XDA forum:

"I had the issue in stock kernel and I moved to Boeffla kernel to check if the issue gets resolved but still every time the mobile goes to sleep wi-fi gets turned off. I will have to manually re-enable the wi-fi for it to start working."
http://forum.xda-developers.com/showpost.php?p=58477068&postcount=6954

Maybe it's related with different chip manufacturers? I don't know...

**Comment by CyberianIce** [comment]
I have this problem (BCM4330 chip) with all kernels on CM12 still present even in lastest nightlies.

**Comment by Guido-glx** [comment]
Mine says bcm4334_B2, and keeps disconnecting

**Comment by CyberianIce** [comment]
* correction 4334 is mine

**Comment by mpq1671** [comment]
In my case it happens when my router is set to b/g/n mode, changing to b/g solves that issue. Maybe that would help.

**Comment by Guido-glx** [comment]
It seems it's been fixed on latests builds...

**Comment by JustArchi** [comment]
Can't reproduce with AK and latest bcmdhd drivers anymore.
