### ISSUE TITLE
Android Wear

### ISSUE THREAD

**Issue by Liko2127** [ArchiDroid/android_device_samsung_i9300#90]
Hello,

my moto 360 can't connect with Android Wear. Still stay in "Connecting...."

In fact I can connect my 360 in Params > BT, but no with Android Wear and so my watch can't connect to my phone.

**Comment by JustArchi** [comment]
Nobody from us owns moto 360 IIRC, unless you provide us with logs, nobody will look into that issue.

**Comment by Grommish** [comment]
If you've flashed a ROM, you'll need to do a Factory Reset on the watch.  At least, that's how I've always corrected that issue with any ROM I've flashed and the 360.

**Comment by JustArchi** [comment]
Not device-based, the only BT bug on our side is with calls.

**Comment by Liko2127** [comment]
It's ok after a factory reset on the watch. But the only problem is not just with call with BT. I can't use my phone with my car. BT crash on connexion (the tethring force close)

**Comment by JustArchi** [comment]
This is not device-based anyway, so we simply don't care.
