### ISSUE TITLE
Volume buttons for screen-off skipping songs not working in CM 5.1 Weekly 3

### ISSUE THREAD

**Issue by flither** [ArchiDroid/android_device_samsung_i9300#94]
My first bug report here,  sorry if not appriorate. Exactly as in a header above, though Playback Control option is checked. Has been reported by other users. Worked fine with my previous flash (CM 12 Weely 10). Tested after clean flash without Gapps.

**Comment by nico-e** [comment]
It works for me man, all i had to do was disable and enable it again... I havent had this problem since (will check back if i do, though)

**Comment by flither** [comment]
Yeah, I've tried that with no luck.
