### ISSUE TITLE
Camera randomly stops working cm-12.1-20150406

### ISSUE THREAD

**Issue by nico-e** [ArchiDroid/android_device_samsung_i9300#95]
The only thing that bothers me is this. I also used to get it with cm11.. Really hoped it would be gone by now :(

**Comment by nico-e** [comment]
Sorry, i just noticed you closed another issue just like mine. May i askeed why it's "Not device-based", though? (help a noob)

**Comment by JustArchi** [comment]
Because it works for me, and you didn't provide any log stating the device-based reason.

Can't reproduce && no logs = I don't care.
