### ISSUE TITLE
Various reboots

### ISSUE THREAD

**Issue by thopiekar** [ArchiDroid/android_device_samsung_i9300#98]
I haven't tried older ROMs, but since the last CM12 builds I experience (various) hard reboots. It often happes after unlocking my device.

Is there a way to find the exact reason? I don't beleave it is because of an app, as there is enough RAM and the device behaves great before it reboots ( no lags / freezes / not using Bluetooth to listen to music, etc.).

**Comment by BLooDLorD** [comment]
i had the same issue. Check your battery, mine died, i replaced it, now everything works fine and no reboots.

**Comment by JustArchi** [comment]
Logs.

Hard reboot -> /proc/last_kmsg after reboot.

**Comment by thopiekar** [comment]
My battery seems to work fine. The percentage seems to be always correct, but will try it if Archi can't find anything, thanks.

last_kmsg: https://mega.co.nz/#!J9xViCya!89HiabPuV8_USX1613eSq137W6KCF2vg48LjhsSiWeY

**Comment by JustArchi** [comment]
No indications of kernel panic.

**Comment by thopiekar** [comment]
Archi: So is it also plausible to you that it can be because of the
battery. I is still curious to me.

**Comment by JustArchi** [comment]
Kernel panic never happened to me, and all issues that did happen are already confirmed on issues page.

I can't reproduce your issue, neither logs say that such issue happened (at all), so there's no way that somebody will look into that.

**Comment by thopiekar** [comment]
OK, thanks. Just bought a new one on eBay. Will see whether it fixes my
problem.
Am 29.04.2015 12:35 nachm. schrieb "Łukasz Domeradzki" <
notifications@github.com>:

**Comment by thopiekar** [comment]
Still happend with new battery after approx 80hours. I beleave that the useful message expected in the last_kmsg gets removed during the boot loop ( where the Samsung logo appears very often). I think there is no other way to get a kmsg, right?
